version: '3.8'

services:
    express-api:
        build:
            context: .
            dockerfile: docker/node-lts/dev/Dockerfile
        volumes:
            - "${PWD}:/opt/app"
        depends_on:
            - expressts-db
        ports:
            - "8090:8080"
            - "5555:5555"
        networks:
            express-ts:

    expressts-db:
        container_name: expressts-postgres_db
        image: postgres
        restart: on-failure
        volumes:
            - db-storage:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        networks:
            express-ts:

volumes:
    db-storage:
        name: express-db-data

networks:
    express-ts:
        name: express-ts
