version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/app
      - ${HOME}/.pnpm-store:/root/.pnpm-store
      - ${HOME}/.pnpm-state.json:/root/.pnpm-state.json
    ports:
      - 8080:8080